version: '2.0'
services:

  api:
    container_name: nest_test
    build: . 
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: postgres_test
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
